//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP12_2COFRELUCAS.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComposicionDB
    {
        public string NModelo { get; set; }
        public string NPieza { get; set; }
        public int CantUsar { get; set; }
    }
}
